name: Docker-ghcr

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "pypi-test-auto-integration2" ]

jobs:
  deploy-package:

    runs-on: ubuntu-latest
    environment: ${{ github.head_ref || github.ref_name }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          poetry_install_options: "--sync --no-root"
          poetry_publish_options: "--dry-run"
          repository_name: "test-pypi"
